#roles/jenkins/tasks/main.yml
---
  - name: 1. Fetch docker version
    shell: docker version 2>&1 | grep Version | awk '{print $2}'
    register: docker_version

  - name: 2. Get script to install Docker
    become: yes
    get_url:
      url: https://raw.githubusercontent.com/sheid1309/DevOps-Scripts/master/docker.sh
      dest: /home/matdecha
      mode: +x
    when: docker_version.stdout == ''

  - name: 3. Execute the script
    become: yes
    shell: /home/matdecha/docker.sh >> /home/matdecha/docker-result.txt
    when: docker_version.stdout == ''

  - name: 4. Check docker located
    become: yes
    command: which docker
    register: docker_dir

  # - name: 5. Run Jenkins container
  #   docker_container:
  #     name: jenkins
  #     image: jenkins/jenkins:latest
  #     ports:
  #       - "8080:8080"
  #       - "50000:50000"
  #     volumes:
  #       - jenkins_home:/var/jenkins_home
  #       - "{{docker_dir.stdout}}:/usr/bin/docker"
  #       - /var/run/docker.sock:/var/run/docker.sock

  - name: 5. Run Jenkins container with docker:sock mounted
    become: yes
    command: 'docker run -dit --name jenkins -p 8080:8080 -p 50000:50000 --mount type=volume,source=jenkins_home,target=/var/jenkins_home -v {{ docker_dir.stdout }}:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock jenkins/jenkins:latest'
  
  - name: 6. Jump into jenkins container as root and assign 777 role to docker.sock
    become: yes
    command: docker exec -u 0 -it jenkins chmod 777 /var/run/docker.sock

  # - name: 2. Start web server
  #   service:
  #     name: httpd
  #     state: started