#roles/webserver/tasks/main.yml
---
    - name: 1. Fetch docker version
      shell: docker version 2>&1 | grep Version | awk '{print $2}'
      register: docker_version

    - name: 2. Get script to install Docker
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/sheid1309/DevOps-Scripts/master/docker.sh
        dest: /home/matdecha
        mode: +x
      when: docker_version.stdout == ''

    - name: 3. Execute the script
      become: yes
      shell: /home/matdecha/docker.sh >> /home/matdecha/docker-result.txt
      when: docker_version.stdout == ''